apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: guestbook2.prod:/Service:/guestbook2.prod-helm-guestbook
  labels:
    app: helm-guestbook
    chart: helm-guestbook-0.1.0
    heritage: Helm
    release: guestbook2.prod
  name: guestbook2.prod-helm-guestbook
spec:
  ports:
    - name: http
      port: 83
      protocol: TCP
      targetPort: http
  selector:
    app: helm-guestbook
    release: guestbook2.prod
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: guestbook2.prod:apps/Deployment:/guestbook2.prod-helm-guestbook
  labels:
    app: helm-guestbook
    chart: helm-guestbook-0.1.0
    heritage: Helm
    release: guestbook2.prod
  name: guestbook2.prod-helm-guestbook
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: helm-guestbook
      release: guestbook2.prod
  template:
    metadata:
      labels:
        app: helm-guestbook
        release: guestbook2.prod
    spec:
      containers:
        - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: http
          name: helm-guestbook
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources: {}
